export const API_ROOT = "http://localhost:4000"

export const FETCH_SHIPMENTS_STARTED = 'FETCH_SHIPMENTS_STARTED';
export const SET_ALL_SHIPMENTS = 'SET_ALL_SHIPMENTS';
export const FETCH_SHIPMENTS_FAILURE = 'FETCH_SHIPMENTS_FAILURE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';