export const FETCH_LOGISTICS_STARTED = 'FETCH_LOGISTICS_STARTED';
export const SET_ALL_LOGISTICS = 'SET_ALL_LOGISTICS';
export const FETCH_LOGISTICS_FAILURE = 'FETCH_LOGISTICS_FAILURE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';